name: in_app_update_flutter
description: "A Flutter plugin to prompt users for in-app updates using StoreKit on iOS and Play Core API on Android."
version: 3.0.1
repository: https://github.com/buildwithpulkit/in_app_update_flutter.git
homepage: https://github.com/buildwithpulkit/in_app_update_flutter
issue_tracker: https://github.com/buildwithpulkit/in_app_update_flutter/issues
topics:
  - in-app-update
  - app-store
  - play-store
  - force-update
  - soft-update

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.pulkitagarwal.in_app_update_flutter
        pluginClass: InAppUpdateFlutterPlugin
      ios:
        pluginClass: InAppUpdateFlutterPlugin
